import { TILE } from './player.js';

const GROUND_Y = 560;
const GROUND_H = 40;

// Each entry: { type: 'ground'|'block'|'spike', x, y, w?, h? }
// Spikes are triangles with base TILE wide, height TILE tall, tip pointing up.
// Ground is a full-width floor strip.
// LEVEL_DATA generated by Copilot CLI — injected below.
export const LEVEL_DATA = [
  { type: 'ground', x: -200, y: GROUND_Y, w: 99999, h: GROUND_H },

  // --- Warm-up: isolated single spikes with long recovery gaps ---
  { type: 'spike', x: 640,  y: GROUND_Y - TILE },
  { type: 'spike', x: 960,  y: GROUND_Y - TILE },
  { type: 'spike', x: 1280, y: GROUND_Y - TILE },
  { type: 'spike', x: 1600, y: GROUND_Y - TILE },

  // --- First platform reads: low blocks with safe exits ---
  { type: 'block', x: 1960, y: GROUND_Y - TILE, w: TILE,     h: TILE },
  { type: 'block', x: 2240, y: GROUND_Y - TILE, w: TILE * 2, h: TILE },
  { type: 'spike', x: 2520, y: GROUND_Y - TILE },

  // --- Intro to pairs: forgiving approach and exit space ---
  { type: 'spike', x: 2920, y: GROUND_Y - TILE },
  { type: 'spike', x: 2960, y: GROUND_Y - TILE },
  { type: 'block', x: 3360, y: GROUND_Y - TILE, w: TILE,     h: TILE },
  { type: 'spike', x: 3680, y: GROUND_Y - TILE },

  // --- Triple-block staircase: climb to an elevated platform ---
  { type: 'block', x: 4080, y: GROUND_Y - TILE,     w: TILE * 3, h: TILE },
  { type: 'block', x: 4360, y: GROUND_Y - TILE * 2, w: TILE * 3, h: TILE },
  { type: 'block', x: 4640, y: GROUND_Y - TILE * 3, w: TILE * 3, h: TILE },

  // --- Elevated platform: familiar spike rhythm on higher ground ---
  { type: 'block', x: 4920, y: GROUND_Y - TILE * 3, w: TILE * 6, h: TILE },
  { type: 'spike', x: 5040, y: GROUND_Y - TILE * 4 },
  { type: 'spike', x: 5200, y: GROUND_Y - TILE * 4 },

  // --- Cascade back down to the base lane ---
  { type: 'block', x: 5480, y: GROUND_Y - TILE * 2, w: TILE * 3, h: TILE },
  { type: 'block', x: 5760, y: GROUND_Y - TILE,     w: TILE * 3, h: TILE },

  // --- Final check: return to the original ground rhythm ---
  { type: 'spike', x: 6200, y: GROUND_Y - TILE },
  { type: 'spike', x: 6520, y: GROUND_Y - TILE },
  { type: 'block', x: 6840, y: GROUND_Y - TILE, w: TILE * 2, h: TILE },
  { type: 'spike', x: 7240, y: GROUND_Y - TILE },

  // --- Win marker (safe platform) ---
  { type: 'block', x: 7640, y: GROUND_Y - TILE, w: TILE * 4, h: TILE },
];

export const LEVEL_LENGTH = 8120;

export class Level {
  constructor() {
    this.cameraX = 0;
    this.speed = 3.2;
  }

  getVisible() {
    return LEVEL_DATA.filter(o =>
      (o.x + (o.w || TILE)) >= this.cameraX - 100 &&
      o.x <= this.cameraX + 900
    );
  }

  update() {
    this.cameraX += this.speed;
  }

  get complete() {
    return this.cameraX >= LEVEL_LENGTH;
  }
}
